name: specarmobile
description: "SpeCar Mobile App"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # Localization
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_crashlytics: ^4.2.0
  firebase_core: ^3.9.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  bloc_concurrency: ^0.2.5
  rxdart: ^0.28.0
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  skeletonizer: ^1.4.2
  go_router: ^14.6.2
  flutter_gen: ^5.8.0
  hydrated_bloc: ^9.1.5
  google_fonts: ^6.2.1
  onesignal_flutter: ^5.2.9
  injectable: ^2.5.0
  get_it: ^8.0.3

dev_dependencies:
  build_runner: ^2.4.14
  flutter_gen_runner: ^5.8.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.2
  json_serializable: ^6.9.0
  very_good_analysis: ^7.0.0

flutter_gen:
  output: lib/src/common/gen/
  line_length: 800

scripts:
  bwatch: dart run build_runner watch --delete-conflicting-outputs

flutter:
  uses-material-design: true
